marker_scale: 0.5

platform: "bluefox_uav_gazebo"

local_mapping:
  using_external_slam_pts: True
  verbose_submap_construction: True

  keyframe_dist_thr: 4
  slam_filtering_enabled: False

  smap_fragmentation_dist: 20000
  n_sphere_samples_per_update: 300
  carryover_dist: 4
  max_sphere_sampling_z : 20

  surfel_resolution: 0.3
  frontier_resolution: 1.5

  min_sphere_rad: 2

  fcu_frame: 'uav1/fcu'
  odom_frame: 'global'
  camera_frame: 'cam0'

  img_topic: '/uav1/vio/camera/image_raw/compressed'
  slampoints_topic: '/ov_msckf/points_slam'

  get_camera_calib_from_topic: False
  camera_info_topic: '/uav1/vio/camera/camera_info'

  ofs_pts_enabled: True
  ofs_pts_dist: 15
  ofs_min_parallax: 0.07
  ofs_pts_always_active: False #DANGEROUS if True
  ofs_ignore_tracking: False #DANGEROUS if True
  ofs_tracking_buffer_len: 10

local_nav:
  enabled: True

  # uav_radius: 0.8
  # safety_replanning_trigger_odist: 1.5
  # min_planning_odist: 1.8
  # max_planning_odist: 8
  # safety_weight: 50

  # GARAGE 
  uav_radius: 0.8
  safety_replanning_trigger_odist: 1.0
  min_planning_odist: 1.6
  max_planning_odist: 8
  safety_weight: 50

  max_rrt_step_size: 0.8
  max_heading_change_per_m: 0.314159 
  path_abandon_time: 8

  clearing_dist: 1.5
  rrt_clearing_dist: 3
  reaching_dist: 1
  out_path_resolution: 0.5

  local_exploration_radius: 15
  # exploration_goal_blocking_dist: 7
  # exploration_goal_blocking_dist: 7
  exploration_goal_blocking_dist: 5

  # predicted_trajectory_topic: '/uav1/control_manager/mpc_tracker/prediction_full_state'
  predicted_trajectory_topic: '/uav1/control_manager/mpc_tracker/predicted_trajectory_debugging'
  output_path_topic: '/uav1/trajectory_generation/path'

  frontier_visibility_dist: 10
  min_num_frontiers_per_goal: 7

exploration_safety_area:
  enabled: False

  # CRANE WORLD 
  x_min: -10
  x_max: 10
  y_min: -10
  y_max: 10
  z_min: -10
  z_max: 10

global_nav:
  enabled: False
  testing_mchunk_filename: "threeroom_big_to_left_end.pickle"
