marker_scale: 0.15

platform: "tello"

local_mapping:
  using_external_slam_pts: False
  verbose_submap_construction: True

  keyframe_dist_thr: 0.8
  slam_filtering_enabled: True

  smap_fragmentation_dist: 10
  n_sphere_samples_per_update: 100
  carryover_dist: 2.5
  max_sphere_sampling_z : 10

  surfel_resolution: 0.8
  frontier_resolution: 1

  min_sphere_rad: 0.1

local_nav:
  enabled: true
  uav_radius: 0.4
  safety_replanning_trigger_odist: 0.3
  min_planning_odist: 0.3
  max_planning_odist: 2

  max_rrt_step_size: 0.05
  # max_heading_change_per_m: 0.314159 
  max_heading_change_per_m: 0.5 
  path_abandon_time: 8

  clearing_dist: 1.5
  reaching_dist: 0.8
  out_path_resolution: 0.5

global_nav:
  enabled: False
  testing_mchunk_filename: "threeroom_big_to_left_end.pickle"

  # TODO - FIX ISSUES WITH 0 IMG POINTs
  # TODO - chheck param values so they align with what i used before
  # TODO - disable global shit with param
  # TODO - visualize tracking again
  # TODO - visualise nav
  # TODO - TRY GETTING MORE POINTS
