marker_scale: 0.15

platform: "tello"

local_mapping:
  using_external_slam_pts: False
  verbose_submap_construction: True

  keyframe_dist_thr: 0.8
  slam_filtering_enabled: True

  smap_fragmentation_dist: 66666
  n_sphere_samples_per_update: 400
  carryover_dist: 2.5
  max_sphere_sampling_z : 10

  surfel_resolution: 0.2
  frontier_resolution: 0.8

  min_sphere_rad: 0.1

local_nav:
  enabled: True
  uav_radius: 0.4
  safety_replanning_trigger_odist: 0.5
  min_planning_odist: 1 # is halved for free space
  max_planning_odist: 3
  safety_weight: 10

  max_rrt_step_size: 0.3
  max_heading_change_per_m: 0.3 
  path_abandon_time: 2

  clearing_dist: 1.5
  rrt_clearing_dist: 3
  reaching_dist: 0.5
  out_path_resolution: 0.5

  local_exploration_radius: 20
  exploration_goal_blocking_dist: 3

global_nav:
  enabled: False
  testing_mchunk_filename: "threeroom_big_to_left_end.pickle"

  # TODO - FIX ISSUES WITH 0 IMG POINTs
  # TODO - chheck param values so they align with what i used before
  # TODO - disable global shit with param
  # TODO - visualize tracking again
  # TODO - visualise nav
  # TODO - TRY GETTING MORE POINTS
